QUIZ_SIZE = 10
OPTIONS_NUM = 7


questions_source = [
    ('Какой метод используется для отправки текстового сообщения в aiogram?',
     ['send_message()', 'post_message()', 'text_send()', 'message_send()', 'send_text()', 'transmit_message()',
      'deliver_text()'],
     'send_message()'),
    ('Какой объект представляет собой CallbackQuery в aiogram?',
     ['UserQuery', 'InlineQuery', 'CallbackResponse', 'ButtonCallback', 'ResponseQuery', 'QueryCallback',
      'UserResponse'],
     'ButtonCallback'),
    ('Как получить ID чата из объекта Message в aiogram?',
     ['message.id()', 'message.chat_id()', 'message.get_chat_id()', 'message.chat.id', 'get_id(message)',
      'chat_id(message)', 'fetch_chat_id(message)'],
     'message.chat.id'),
    ('Как отправить фотографию с подписью в aiogram?',
     ['send_photo()', 'post_picture()', 'transmit_image()', 'photo_send()', 'deliver_captioned_photo()', 'send_image()',
      'captioned_send_photo()'],
     'photo_send()'),
    ('Какой метод используется для добавления кнопок в InlineKeyboardMarkup в aiogram?',
     ['add_button()', 'insert_button()', 'append_button()', 'row_add_button()', 'insert_row()', 'add_row()',
      'attach_button_row()'],
     'insert_row()'),
    ('Какой метод используется для отправки голосового сообщения в aiogram?',
     ['voice_send()', 'send_audio()', 'transmit_voice()', 'audio_deliver()', 'send_sound()', 'voice_message()',
      'deliver_audio()'],
     'audio_deliver()'),
    ('Как обработать текстовое сообщение в aiogram с использованием Middleware?',
     ['middleware.process_text()', 'process_message_text()', 'text_middleware_handler()', 'on_text_middleware()',
      'handle_text()', 'text_processing_middleware()', 'process_text_message()'],
     'on_text_middleware()'),
    ('Как получить объект Chat из CallbackQuery в aiogram?',
     ['query.get_chat()', 'callback_chat(query)', 'chat_from_query(query)', 'query.message.chat', 'fetch_chat(query)',
      'get_callback_chat(query)', 'chat(query.callback)'],
     'query.message.chat'),
    ('Как отправить стикер в aiogram?',
     ['send_sticker()', 'post_emoji()', 'transmit_emoticon()', 'sticker_send()', 'deliver_emoji_sticker()',
      'send_emoji()', 'post_sticker()'],
     'send_sticker()'),
    ('Как изменить клавиатуру у сообщения с использованием edit_message_reply_markup в aiogram?',
     ['change_keyboard_markup()', 'modify_reply_keyboard()', 'edit_markup()', 'edit_message_reply_markup()',
      'update_keyboard()', 'alter_reply_markup()', 'adjust_keyboard_markup()'],
     'edit_message_reply_markup()'),
    ('Как отправить сообщение с HTML-форматированием текста в aiogram?',
     ['send_html_message()', 'html_send()', 'deliver_formatted_message()', 'send_message(html=True)',
      'formatted_text_send()', 'post_html()', 'message_html()'],
     'send_message(html=True)'),
    ('Как получить список доступных команд бота в aiogram?',
     ['get_bot_commands()', 'fetch_commands()', 'bot.get_commands()', 'list_bot_commands()', 'retrieve_commands()',
      'available_bot_commands()', 'bot_commands_list()'],
     'bot.get_commands()'),
    ('Как отправить видеофайл в aiogram?',
     ['send_video()', 'post_movie()', 'video_send()', 'transmit_video()', 'deliver_clip()', 'send_media()',
      'post_video()'],
     'video_send()'),
    ('Как получить callback_data из InlineKeyboardButton в aiogram?',
     ['button.callback_data()', 'get_button_data()', 'button.get_callback_data()', 'fetch_callback_data(button)',
      'inline_button_data()', 'extract_button_data()', 'button.callback()'],
     'button.get_callback_data()'),
    ('Как обработать InlineQuery в aiogram?',
     ['process_inline_query()', 'handle_query()', 'inline_query_handler()', 'query_process()', 'respond_inline()',
      'process_query_inline()', 'inline_handler()'],
     'inline_query_handler()'),
    ('Как отправить аудиофайл с использованием aiogram?',
     ['audio_send()', 'send_music()', 'post_music()', 'transmit_music()', 'transmit_audio()', 'post_audio()',
      'send_audio()'],
     'send_audio()'),
    ('Как установить действие на InlineKeyboardButton в aiogram?',
     ['set_button_action()', 'button_action_set()', 'inline_button_set_action()', 'action_set_button()',
      'set_inline_button_action()', 'assign_button_action()', 'set_button_behavior()'],
     'inline_button_set_action()'),
    ('Как отправить местоположение (location) в aiogram?',
     ['send_location()', 'deliver_coordinates()', 'post_map_location()', 'post_map_position()', 'transmit_position()',
      'position_send()', 'location_send()'],
     'location_send()'),
    ('Как добавить клавиатуру к сообщению с помощью InlineKeyboardMarkup в aiogram?',
     ['add_inline_keyboard()', 'attach_keyboard_markup()', 'add_keyboard_markup()', 'inline_markup_add()',
      'inline_keyboard_add()', 'attach_inline_keyboard()', 'add_markup_keyboard()'],
     'inline_keyboard_add()'),
    ('Как получить доступ к тексту сообщения из объекта CallbackQuery в aiogram?',
     ['query.get_message_text()', 'callback_message_text()', 'fetch_query_message_text()', 'query.message.text',
      'get_callback_text(query)', 'callback_text()', 'query_text_message()'],
     'query.message.text'),
    ('Как отправить JSON-данные с использованием библиотеки requests в Python?',
     ['send_json_data()', 'post_request()', 'json_send()', 'requests.post(json=...)', 'transmit_json()',
      'deliver_data()', 'json_post()'],
     'requests.post(json=...)'),
    ('Как создать генератор чисел Фибоначчи в Python?',
     ['fibonacci_generator()', 'generate_fibonacci()', 'fib_sequence()',
      'fib_gen = (x for x in range(2) if x < 2 else fib_gen[-2] + fib_gen[-1])', 'create_fibonacci()',
      'fibonacci_sequence()', 'generate_fibonacci_numbers()'],
     'fib_gen = (x for x in range(2) if x < 2 else fib_gen[-2] + fib_gen[-1])'),
    ('Как обработать исключение в Python с помощью конструкции try-except?',
     ['handle_exception()', 'try_catch_block()', 'except_handling()', 'try:... except:...', 'catch_error()',
      'exception_block()', 'process_exception()'],
     'try:... except:...'),
    ('Как добавить элемент в конец списка в Python?',
     ['list_add_end()', 'append_list()', 'add_to_end()', 'list.append()', 'insert_end()', 'add_list_element()',
      'append_to_list()'],
     'list.append()'),
    ('Как создать словарь в Python?',
     ['create_dict()', 'dict_create()', 'new_dict()', '{}', 'make_dictionary()', 'generate_dict()', 'dict()'],
     '{}'),
    ('Как сортировать список в порядке убывания в Python?',
     ['sort_list(reverse=True)', 'descending_sort()', 'sort(reverse=False)', 'reverse_sort()',
      'list.sort(descending=True)', 'descending_order()', 'order_list(reverse=True)'],
     'sort_list(reverse=True)'),
    ('Как преобразовать строку в список символов в Python?',
     ['string_to_list()', 'convert_string()', 'list(string)', 'str_list()', 'string.convert_to_list()',
      'to_list(string)', 'split_string()'],
     'list(string)'),
    ('Как создать множество (set) в Python?',
     ['make_set()', 'create_set()', 'set_create()', 'set()', 'new_set()', 'generate_set()', 'set_make()'],
     'set()'),
    ('Как определить, существует ли файл в определенной директории в Python?',
     ['file_exists()', 'check_file()', 'exists_file()', 'os.path.isfile()', 'is_file()', 'file_check()',
      'validate_file()'],
     'os.path.isfile()'),
    ('Как использовать генератор случайных чисел в диапазоне в Python?',
     ['random_gen()', 'generate_random()', 'random_numbers()', 'random.randint()', 'range_random()', 'gen_random()',
      'randint()'],
     'random.randint()')
]
