TECH_QUIZ_SIZE = 10
OPTIONS_NUM = 7


tech_questions_source = [
    ('Какой метод используется для отправки текстового сообщения в aiogram?',
     ['send_message()', 'post_message()', 'text_send()', 'message_send()', 'send_text()', 'transmit_message()',
      'deliver_text()'],
     'send_message()'),
    ('Какой объект представляет собой CallbackQuery в aiogram?',
     ['UserQuery', 'InlineQuery', 'CallbackResponse', 'ButtonCallback', 'ResponseQuery', 'QueryCallback',
      'UserResponse'],
     'ButtonCallback'),
    ('Как получить ID чата из объекта Message в aiogram?',
     ['message.id()', 'message.chat_id()', 'message.get_chat_id()', 'message.chat.id', 'get_id(message)',
      'chat_id(message)', 'fetch_chat_id(message)'],
     'message.chat.id'),
    ('Как отправить фотографию с подписью в aiogram?',
     ['send_photo()', 'post_picture()', 'transmit_image()', 'photo_send()', 'deliver_captioned_photo()', 'send_image()',
      'captioned_send_photo()'],
     'photo_send()'),
    ('Какой метод используется для добавления кнопок в InlineKeyboardMarkup в aiogram?',
     ['add_button()', 'insert_button()', 'append_button()', 'row_add_button()', 'insert_row()', 'add_row()',
      'attach_button_row()'],
     'insert_row()'),
    ('Какой метод используется для отправки голосового сообщения в aiogram?',
     ['voice_send()', 'send_audio()', 'transmit_voice()', 'audio_deliver()', 'send_sound()', 'voice_message()',
      'deliver_audio()'],
     'audio_deliver()'),
    ('Как обработать текстовое сообщение в aiogram с использованием Middleware?',
     ['middleware.process_text()', 'process_message_text()', 'text_middleware_handler()', 'on_text_middleware()',
      'handle_text()', 'text_processing_middleware()', 'process_text_message()'],
     'on_text_middleware()'),
    ('Как получить объект Chat из CallbackQuery в aiogram?',
     ['query.get_chat()', 'callback_chat(query)', 'chat_from_query(query)', 'query.message.chat', 'fetch_chat(query)',
      'get_callback_chat(query)', 'chat(query.callback)'],
     'query.message.chat'),
    ('Как отправить стикер в aiogram?',
     ['send_sticker()', 'post_emoji()', 'transmit_emoticon()', 'sticker_send()', 'deliver_emoji_sticker()',
      'send_emoji()', 'post_sticker()'],
     'send_sticker()'),
    ('Как изменить клавиатуру у сообщения с использованием edit_message_reply_markup в aiogram?',
     ['change_keyboard_markup()', 'modify_reply_keyboard()', 'edit_markup()', 'edit_message_reply_markup()',
      'update_keyboard()', 'alter_reply_markup()', 'adjust_keyboard_markup()'],
     'edit_message_reply_markup()'),
    ('Как отправить сообщение с HTML-форматированием текста в aiogram?',
     ['send_html_message()', 'html_send()', 'deliver_formatted_message()', 'send_message(html=True)',
      'formatted_text_send()', 'post_html()', 'message_html()'],
     'send_message(html=True)'),
    ('Как получить список доступных команд бота в aiogram?',
     ['get_bot_commands()', 'fetch_commands()', 'bot.get_commands()', 'list_bot_commands()', 'retrieve_commands()',
      'available_bot_commands()', 'bot_commands_list()'],
     'bot.get_commands()'),
    ('Как отправить видеофайл в aiogram?',
     ['send_video()', 'post_movie()', 'video_send()', 'transmit_video()', 'deliver_clip()', 'send_media()',
      'post_video()'],
     'video_send()'),
    ('Как получить callback_data из InlineKeyboardButton в aiogram?',
     ['button.callback_data()', 'get_button_data()', 'button.get_callback_data()', 'fetch_callback_data(button)',
      'inline_button_data()', 'extract_button_data()', 'button.callback()'],
     'button.get_callback_data()'),
    ('Как обработать InlineQuery в aiogram?',
     ['process_inline_query()', 'handle_query()', 'inline_query_handler()', 'query_process()', 'respond_inline()',
      'process_query_inline()', 'inline_handler()'],
     'inline_query_handler()'),
    ('Как отправить аудиофайл с использованием aiogram?',
     ['audio_send()', 'send_music()', 'post_music()', 'transmit_music()', 'transmit_audio()', 'post_audio()',
      'send_audio()'],
     'send_audio()'),
    ('Как установить действие на InlineKeyboardButton в aiogram?',
     ['set_button_action()', 'button_action_set()', 'inline_button_set_action()', 'action_set_button()',
      'set_inline_button_action()', 'assign_button_action()', 'set_button_behavior()'],
     'inline_button_set_action()'),
    ('Как отправить местоположение (location) в aiogram?',
     ['send_location()', 'deliver_coordinates()', 'post_map_location()', 'post_map_position()', 'transmit_position()',
      'position_send()', 'location_send()'],
     'location_send()'),
    ('Как добавить клавиатуру к сообщению с помощью InlineKeyboardMarkup в aiogram?',
     ['add_inline_keyboard()', 'attach_keyboard_markup()', 'add_keyboard_markup()', 'inline_markup_add()',
      'inline_keyboard_add()', 'attach_inline_keyboard()', 'add_markup_keyboard()'],
     'inline_keyboard_add()'),
    ('Как получить доступ к тексту сообщения из объекта CallbackQuery в aiogram?',
     ['query.get_message_text()', 'callback_message_text()', 'fetch_query_message_text()', 'query.message.text',
      'get_callback_text(query)', 'callback_text()', 'query_text_message()'],
     'query.message.text'),
    ('Как отправить JSON-данные с использованием библиотеки requests в Python?',
     ['send_json_data()', 'post_request()', 'json_send()', 'requests.post(json=...)', 'transmit_json()',
      'deliver_data()', 'json_post()'],
     'requests.post(json=...)'),
    ('Как создать генератор чисел Фибоначчи в Python?',
     ['fibonacci_generator()', 'generate_fibonacci()', 'fib_sequence()',
      'fib_gen = (x for x in range(2) if x < 2 else fib_gen[-2] + fib_gen[-1])', 'create_fibonacci()',
      'fibonacci_sequence()', 'generate_fibonacci_numbers()'],
     'fib_gen = (x for x in range(2) if x < 2 else fib_gen[-2] + fib_gen[-1])'),
    ('Как обработать исключение в Python с помощью конструкции try-except?',
     ['handle_exception()', 'try_catch_block()', 'except_handling()', 'try:... except:...', 'catch_error()',
      'exception_block()', 'process_exception()'],
     'try:... except:...'),
    ('Как добавить элемент в конец списка в Python?',
     ['list_add_end()', 'append_list()', 'add_to_end()', 'list.append()', 'insert_end()', 'add_list_element()',
      'append_to_list()'],
     'list.append()'),
    ('Как создать словарь в Python?',
     ['create_dict()', 'dict_create()', 'new_dict()', '{}', 'make_dictionary()', 'generate_dict()', 'dict()'],
     '{}'),
    ('Как сортировать список в порядке убывания в Python?',
     ['sort_list(reverse=True)', 'descending_sort()', 'sort(reverse=False)', 'reverse_sort()',
      'list.sort(descending=True)', 'descending_order()', 'order_list(reverse=True)'],
     'sort_list(reverse=True)'),
    ('Как преобразовать строку в список символов в Python?',
     ['string_to_list()', 'convert_string()', 'list(string)', 'str_list()', 'string.convert_to_list()',
      'to_list(string)', 'split_string()'],
     'list(string)'),
    ('Как создать множество (set) в Python?',
     ['make_set()', 'create_set()', 'set_create()', 'set()', 'new_set()', 'generate_set()', 'set_make()'],
     'set()'),
    ('Как определить, существует ли файл в определенной директории в Python?',
     ['file_exists()', 'check_file()', 'exists_file()', 'os.path.isfile()', 'is_file()', 'file_check()',
      'validate_file()'],
     'os.path.isfile()'),
    ('Как использовать генератор случайных чисел в диапазоне в Python?',
     ['random_gen()', 'generate_random()', 'random_numbers()', 'random.randint()', 'range_random()', 'gen_random()',
      'randint()'],
     'random.randint()')
]

psycho_questions_source = [
    ('Доминантность (D):', 'Как вы реагируете на вызов к действию?',
     [(7, 'a) Принимаю инициативу'), (6, 'b) Обсуждаю с командой'), (5, 'c) Рассматриваю варианты'),
      (4, 'd) Действую сразу'), (3, 'e) Предпочитаю тщательное планирование'),
      (2, 'f) Перекладываю ответственность на других'), (1, 'g) Не реагирую на вызовы')]),
    ('Доминантность (D):', 'Как вы реагируете на оппозицию в команде?',
     [(7, 'a) Принимаю решительные меры'), (6, 'b) Пытаюсь убедить других в своей точке зрения'),
      (5, 'c) Ищу компромисс'), (4, 'd) Выслушиваю точки зрения всех'), (3, 'e) Игнорирую оппозицию'),
      (2, 'f) Отстаиваю свою точку зрения настойчиво'), (1, 'g) Ухожу от конфликтов')]),
    ('Доминантность (D):', 'Как вы реагируете на непредвиденные трудности в проекте?',
     [(7, 'a) Немедленно решаю проблемы'), (6, 'b) Созваниваюсь с командой для совместного поиска решения'),
      (5, 'c) Анализирую ситуацию и выбираю оптимальный вариант'), (4, 'd) Принимаю вызов и ищу новые пути решения'),
      (3, 'e) Доверяю команде и предлагаю совместные решения'),
      (2, 'f) Ищу компромисс между различными точками зрения'),
      (1, 'g) Делегирую решение проблемы другому члену команды')]),
    ('Влиятельность (I):', 'Как важно для вас быть в центре внимания?',
     [(7, 'a) Очень важно'), (6, 'b) Важно'), (5, 'c) Нейтрально'), (4, 'd) Менее важно'), (3, 'e) Совсем не важно'),
      (2, 'f) Предпочитаю работать в тени'), (1, 'g) Избегаю общественных мероприятий')]),
    ('Влиятельность (I):', 'Как часто вы инициируете новые проекты или идеи?',
     [(7, 'a) Почти постоянно'), (6, 'b) Часто'), (5, 'c) Иногда'), (4, 'd) Редко'), (3, 'e) Совсем не инициирую'),
      (2, 'f) Предпочитаю работать над существующими проектами'), (1, 'g) Предоставляю идеи другим')]),
    ('Влиятельность (I):', 'Как часто вы ищете обратную связь от коллег или руководства?',
     [(7, 'a) Регулярно провожу обзор производительности'), (6, 'b) Часто спрашиваю мнение других'),
      (5, 'c) Иногда уточняю, как могу улучшить свою работу'), (4, 'd) Редко обращаю внимание на мнение окружающих'),
      (3, 'e) Считаю, что мой вклад очевиден и не требует оценки'), (2, 'f) Предпочитаю анонимную обратную связь'),
      (1, 'g) Считаю, что обратная связь не имеет большого значения')]),
    ('Стабильность (S):', 'Как вы реагируете на изменения в рабочем процессе?',
     [(7, 'a) Принимаю вызов'), (6, 'b) Предпочитаю постепенные изменения'), (5, 'c) Адаптируюсь'),
      (4, 'd) Сначала сопротивляюсь, но потом принимаю'), (3, 'e) Трудно принимаю изменения'),
      (2, 'f) Стремлюсь к стабильности'), (1, 'g) Постоянно ищу новые возможности')]),
    ('Стабильность (S):', 'Как вы обычно реагируете на стрессовые ситуации?',
     [(7, 'a) Остаюсь спокоен и сосредоточен'), (6, 'b) Пытаюсь уменьшить напряжение среди коллег'),
      (5, 'c) Ищу поддержку у других'), (4, 'd) Решаю проблемы шаг за шагом'), (3, 'e) Впадаю в панику'),
      (2, 'f) Стремлюсь к личной уединенности'), (1, 'g) Забываю о проблемах и отвлекаюсь')]),
    ('Стабильность (S):', 'Как вы предпочитаете организовывать свое рабочее пространство?',
     [(7, 'a) С учетом функциональности и эффективности'), (6, 'b) С учетом комфорта и коллективного настроения'),
      (5, 'c) Устраиваю рабочее пространство с учетом изменений'),
      (4, 'd) Предпочитаю традиционные методы организации'),
      (3, 'e) Стремлюсь к индивидуальному рабочему пространству'), (2, 'f) Следую корпоративным стандартам'),
      (1, 'g) Оставляю рабочее пространство неорганизованным')]),
    ('Тщательность (C):', 'Как часто вы проверяете свою работу на ошибки?',
     [(7, 'a) Редко'), (6, 'b) Иногда'), (5, 'c) Почти всегда'), (4, 'd) Всегда'),
      (3, 'e) Не обращаю внимания на детали'), (2, 'f) Заботливо следую инструкциям'), (1, 'g) Пренебрегаю деталями')]),
    ('Тщательность (C):', 'Как вы реагируете на неопределенность в задачах?',
     [(7, 'a) Развиваю четкий план действий'), (6, 'b) Консультируюсь с опытными коллегами'),
      (5, 'c) Пробую различные подходы'), (4, 'd) Просматриваю подробности исходной задачи'),
      (3, 'e) Заинтересован в общих целях, а не деталях'), (2, 'f) Стремлюсь к предсказуемости'),
      (1, 'g) Принимаю ситуацию как есть')]),
    ('Тщательность (C):', 'Как вы относитесь к выполнению задач, требующих долгого анализа?',
     [(7, 'a) Люблю разбираться в деталях и анализировать все аспекты'),
      (6, 'b) Советуюсь с коллегами, прежде чем принимать решение'),
      (5, 'c) Делаю анализ только в случае крайней необходимости'), (4, 'd) Предпочитаю срочные задачи'),
      (3, 'e) Склонен доверять своему интуитивному решению'),
      (2, 'f) Задачи, требующие долгого анализа, вызывают стресс'),
      (1, 'g) Делегирую задачи, требующие глубокого анализа')])
]
